// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ConversationMemberStatus string

const (
	ConversationMemberStatusActive   ConversationMemberStatus = "active"
	ConversationMemberStatusDeactive ConversationMemberStatus = "deactive"
)

func (e *ConversationMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationMemberStatus(s)
	case string:
		*e = ConversationMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationMemberStatus: %T", src)
	}
	return nil
}

type NullConversationMemberStatus struct {
	ConversationMemberStatus ConversationMemberStatus
	Valid                    bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.ConversationMemberStatus, nil
}

type Conversation struct {
	ConversationID   string         `json:"conversation_id"`
	ConversationName sql.NullString `json:"conversation_name"`
	CreatedAt        time.Time      `json:"created_at"`
}

type ConversationMember struct {
	UserID         string                       `json:"user_id"`
	ConversationID string                       `json:"conversation_id"`
	Status         NullConversationMemberStatus `json:"status"`
	CreatedAt      time.Time                    `json:"created_at"`
}

type User struct {
	UserID            string    `json:"user_id"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
