// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Habit struct {
	HabitID               int64         `json:"habit_id"`
	Title                 string        `json:"title"`
	TargetConsecutiveDays int32         `json:"target_consecutive_days"`
	SkillID               sql.NullInt64 `json:"skill_id"`
	UserID                int64         `json:"user_id"`
}

type HabitLog struct {
	UserID   int64 `json:"user_id"`
	HabitID  int64 `json:"habit_id"`
	DateTime int64 `json:"date_time"`
}

type Skill struct {
	SkillID int64  `json:"skill_id"`
	UserID  int64  `json:"user_id"`
	Title   string `json:"title"`
}

type User struct {
	UserID    int64  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
