// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateHabitLog(ctx context.Context, arg CreateHabitLogParams) (HabitLog, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHabit(ctx context.Context, habitID int64) error
	DeleteSkill(ctx context.Context, skillID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetHabitLogsByUser(ctx context.Context, userID int64) ([]HabitLog, error)
	GetHabitsByUser(ctx context.Context, userID int64) ([]Habit, error)
	GetHabitsByUserAndSkill(ctx context.Context, arg GetHabitsByUserAndSkillParams) ([]Habit, error)
	GetLatestHabitLogByUser(ctx context.Context, arg GetLatestHabitLogByUserParams) ([]HabitLog, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListSkillsByUser(ctx context.Context, arg ListSkillsByUserParams) ([]Skill, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
}

var _ Querier = (*Queries)(nil)
