name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  
  test:
    name: DB-Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run test
      run: go test -v ./...